- name: "Destroy Custom Subnetwork"
  gce_net: 
    name: "{{ vpc_network_name }}"
    credentials_file: "{{ credentials_file }}"
    mode: custom
    subnet_name: "{{ private_subnet_name }}"
    subnet_region: "{{ region }}"
    ipv4_range: "{{ private_subnet_range }}"
    service_account_email: "{{ service_account_email }}"
    state: "absent"
    project_id: "{{ project_id }}"

- name: "Destroy Custom VPC Network"
  gce_net:
    name: "{{ vpc_network_name }}"
    credentials_file: "{{ credentials_file }}"
    service_account_email: "{{ service_account_email }}"
    project_id: "{{ project_id }}"
    state: "absent"
